services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: sig
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sig_empresa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
